#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/vendor/autoload.php')) {
    require __DIR__.'/vendor/autoload.php';
} else {
    require __DIR__.'/../../autoload.php';
}

$app = new Symfony\Component\Console\Application('Medlib Installer', '1.0.0');
$app->add(new Medlib\Installer\NewCommand);
$app->add(new Medlib\Installer\RegisterCommand);
$app->add(new Medlib\Installer\TokenCommand);

$app->run();